import express from 'express';
import path from 'path';
import dotenv from 'dotenv';
import { createServer as createViteServer } from 'vite';

// Load environmental variables
dotenv.config();

// Import central controllers & sub-routers from MVC Backend
import authRouter from './backend/src/routes/authRoutes.ts';
import productRouter from './backend/src/routes/productRoutes.ts';
import watchlistRouter from './backend/src/routes/watchlistRoutes.ts';
import alertRouter from './backend/src/routes/alertRoutes.ts';
import historyRouter from './backend/src/routes/historyRoutes.ts';
import shoppingApiRouter from './backend/src/routes/shoppingApiRoutes.ts';
import adminRouter from './backend/src/routes/adminRoutes.ts';
import dashboardRouter from './backend/src/routes/dashboardRoutes.ts';
import { errorHandler } from './backend/src/middleware/errorHandler.ts';
import { globalApiLimiter } from './backend/src/middleware/rateLimiter.ts';
import { initializeDatabase } from './backend/src/config/initDb.ts';
import { startScheduler } from './backend/src/services/scheduler.ts';

async function startServer() {
  console.log('[Full-Stack Server] Initializing process context...');

  const app = express();
  const PORT = parseInt(process.env.PORT || '3000', 10);

  // Initialize database schema
  try {
    await initializeDatabase();
    console.log('[PostgreSQL] Database schema initial check done. Launching background scheduler.');
    startScheduler();
  } catch (err) {
    console.error('[PostgreSQL] Database initialization failed:', err);
  }

  // 1. Core Request Middlewares: Body parser with 100kb limit & rate limiting
  app.use(express.json({ limit: '100kb' }));
  app.use(express.urlencoded({ extended: true, limit: '100kb' }));
  app.use('/api', globalApiLimiter);

  // 2. REST API Resource Route Maps (Eliminates Route Prefix Mismatches!)
  app.use('/api/auth', authRouter);
  app.use('/api/products', productRouter);
  app.use('/api/watchlist', watchlistRouter);
  app.use('/api/alerts', alertRouter);
  app.use('/api/history', historyRouter);
  app.use('/api/admin', adminRouter);
  app.use('/api/dashboard', dashboardRouter);
  app.use('/api/stores', shoppingApiRouter);
  app.use('/api', shoppingApiRouter);



  // Root level API health probe
  app.get('/api/health', (req, res) => {
    res.status(200).json({
      status: 'success',
      message: 'Unifed Full-Stack E-Commerce Portal is live and connected!',
      timestamp: new Date().toISOString()
    });
  });

  // 3. Vite Development Middleware Integration vs static production bundle serving
  if (process.env.NODE_ENV !== 'production') {
    console.log('[Vite Middleware] Coupling active React HMR server...');
    const viteInstance = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa'
    });
    
    // Couple Vite asset compilation middlewares
    app.use(viteInstance.middlewares);
  } else {
    console.log('[Static Server] Mounting production web assets in /dist...');
    const distPath = path.resolve(process.cwd(), 'dist');
    
    // Serve static files generated by Vite build phase
    app.use(express.static(distPath));
    
    // Route unmatched paths to spa index to ensure client-side routers work beautifully on refresh
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  // 4. Global Express JSON exception handler (MUST be mounted after routes/middlewares!)
  app.use(errorHandler);

  // 5. Fire up Server
  const server = app.listen(PORT, '0.0.0.0', () => {
    console.log(`================================================================`);
    console.log(`🚀 SENIOR ARCHITECT UNIFIED PORTAL - DEPLOYMENT READY`);
    console.log(`📡 Server running at: http://0.0.0.0:${PORT}`);
    console.log(`🔧 Run Mode: ${process.env.NODE_ENV || 'development'}`);
    console.log(`================================================================`);
  });

  // Gracefully handle unhandled async promise rejections to dodge abrupt crashes
  process.on('unhandledRejection', (err: any) => {
    console.error('[UNHANDLED REJECTION] Graceful shutdown in progress...', err);
    server.close(() => {
      process.exit(1);
    });
  });
}

startServer();
